services:
  - type: web
    name: report-card-generator
    env: python
    plan: starter
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: 'report-card-generator.onrender.com'
      - key: SECRET_KEY
        generateValue: true
